/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mundial_javamysql;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author migue
 */
public class Frmantidopaje extends javax.swing.JFrame {

    /**
     * Creates new form Frmantidopaje
     */
    public Frmantidopaje() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblantidopaje = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lbllugar = new javax.swing.JLabel();
        lbltest = new javax.swing.JLabel();
        btnconsultar = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        txtcodigo = new javax.swing.JTextField();
        txtlugar = new javax.swing.JTextField();
        txtpasotest = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblantidopaje = new javax.swing.JTable();
        btninforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblantidopaje.setText("EXAMEN ANTI-DOPAJE");

        lblcodigo.setText("Codigo del examen:");

        lbllugar.setText("Lugar del examen:");

        lbltest.setText("Pasó el test:");

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        tblantidopaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblantidopaje);

        btninforme.setText("Generar Informe de Exámenes");
        btninforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblantidopaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btninforme))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbltest)
                                        .addGap(53, 53, 53)
                                        .addComponent(txtpasotest, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblcodigo)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbllugar)
                                        .addGap(24, 24, 24)
                                        .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnconsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btninsertar)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnactualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblantidopaje)
                    .addComponent(btninforme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodigo)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllugar)
                    .addComponent(txtlugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltest)
                    .addComponent(txtpasotest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar)
                    .addComponent(btninsertar)
                    .addComponent(btneliminar)
                    .addComponent(btnactualizar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,lugar,pasotest;
        String sql="";
        cod = txtcodigo.getText();
        lugar = txtlugar.getText();
        pasotest = txtpasotest.getText();

        sql = "{ call consultarinfo_antidopaje(?,?,?) }";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblantidopaje.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,lugar,pasotest;
        String sql= "";
        cod = txtcodigo.getText();
        lugar = txtlugar.getText();
        pasotest = txtpasotest.getText();
        sql = "{ call insertarinfo_antidopaje(?,?,?) }";
         try {
             PreparedStatement pst = cn.prepareStatement(sql);
             pst.setString(1,cod);
             pst.setString(2,lugar);
             pst.setString(3,pasotest);

             
             int registro=pst.executeUpdate();
             if (registro>0)
             {
                 JOptionPane.showMessageDialog(null, "Registro almacenado correctamente");
                 limpiar();
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Registro NO almacenado " + e.getMessage());

    } 
    }//GEN-LAST:event_btninsertarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,lugar,pasotest;
        String sql ="";
        cod = txtcodigo.getText();
        lugar = txtlugar.getText();
        pasotest = txtpasotest.getText();
        sql = "{ call eliminarinfo_antidopaje(?,?,?,?) }";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro eliminado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para eliminar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO eliminado" + e.getMessage());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,lugar,pasotest;
        String sql ="";
        cod = txtcodigo.getText();
        lugar = txtlugar.getText();
        pasotest = txtpasotest.getText();
        
        sql = "{ call actualizarinfo_antidopaje(?,?,?) }";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro actualizado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para actualizar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO actualizado" + e.getMessage());
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btninformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformeActionPerformed
        // TODO add your handling code here:
                conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,lugar,pasotest;
        String sql ="";
        cod = txtcodigo.getText();
        lugar = txtlugar.getText();
        pasotest = txtpasotest.getText();
        sql = "SELECT equipo.nombre_equipo,jugadores.fecha from equipo "
            + "INNER JOIN jugadores ON equipo.idjugadores= jugadores.idjugadores";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblantidopaje.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btninformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmantidopaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmantidopaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmantidopaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmantidopaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmantidopaje().setVisible(true);
            }
        });
    }
                    public void limpiar()
    {
        txtcodigo.setText("");
        txtlugar.setText("");
        txtpasotest.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninforme;
    private javax.swing.JButton btninsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblantidopaje;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lbllugar;
    private javax.swing.JLabel lbltest;
    private javax.swing.JTable tblantidopaje;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtlugar;
    private javax.swing.JTextField txtpasotest;
    // End of variables declaration//GEN-END:variables
}
