/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mundial_javamysql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author migue
 */
public class Frmequipos extends javax.swing.JFrame {

    /**
     * Creates new form Frmequipos
     */
    public Frmequipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblequipos = new javax.swing.JLabel();
        lblcodequi = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblpais = new javax.swing.JLabel();
        lblcodhotel = new javax.swing.JLabel();
        lblcodjugador = new javax.swing.JLabel();
        btnconsultar = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        txtcodequipo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtpais = new javax.swing.JTextField();
        txtcodigohotel = new javax.swing.JTextField();
        txtcodigojugador = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblequipos = new javax.swing.JTable();
        btninforme = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblequipos.setText("EQUIPOS");

        lblcodequi.setText("Codigo del equipo:");

        lblnombre.setText("Nombre:");

        lblpais.setText("País:");

        lblcodhotel.setText("Codigo de hotel:");

        lblcodjugador.setText("Codigo del jugador:");

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        tblequipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblequipos);

        btninforme.setText("Generar Informe de Equipos");
        btninforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btninsertar)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnactualizar)
                        .addGap(32, 32, 32))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblnombre)
                            .addComponent(lblcodequi)
                            .addComponent(lblpais)
                            .addComponent(lblcodhotel)
                            .addComponent(lblcodjugador))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(lblequipos))
                                    .addComponent(txtcodequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btninforme)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodigohotel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtcodigojugador, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblequipos)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcodequi)
                            .addComponent(txtcodequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btninforme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpais)
                    .addComponent(txtpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodhotel)
                    .addComponent(txtcodigohotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodjugador)
                    .addComponent(txtcodigojugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar)
                    .addComponent(btninsertar)
                    .addComponent(btneliminar)
                    .addComponent(btnactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
                                conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,pais,idhotel,idjuga;
        String sql="";
        cod = txtcodequipo.getText();
        nom = txtnombre.getText();
        pais = txtpais.getText();
        idhotel = txtcodigohotel.getText();
        idjuga = txtcodigojugador.getText();
        sql = "{ call consultarinfo_equipos(?,?,?,?,?) }";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblequipos.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,pais,idhotel,idjuga;
        String sql= "";
        cod = txtcodequipo.getText();
        nom = txtnombre.getText();
        pais = txtpais.getText();
        idhotel = txtcodigohotel.getText();
        idjuga = txtcodigojugador.getText();
        sql = "{ call insertarinfo_equipos(?,?,?,?,?) }";
         try {
             PreparedStatement pst = cn.prepareStatement(sql);
             pst.setString(1,cod);
             pst.setString(2,nom);
             pst.setString(3,pais);
             pst.setString(4,idhotel);
             pst.setString(5,idjuga);
             
             int registro=pst.executeUpdate();
             if (registro>0)
             {
                 JOptionPane.showMessageDialog(null, "Registro almacenado correctamente");
                 limpiar();
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Registro NO almacenado " + e.getMessage());

    } 
    }//GEN-LAST:event_btninsertarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,pais,idhotel,idjuga;
        String sql ="";
        cod = txtcodequipo.getText();
        nom = txtnombre.getText();
        pais = txtpais.getText();
        idhotel = txtcodigohotel.getText();
        idjuga = txtcodigojugador.getText();
        sql = "{ call eliminarinfo_equipos(?,?,?,?,?) }";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro eliminado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para eliminar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO eliminado" + e.getMessage());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,pais,idhotel,idjuga;
        String sql ="";
        cod = txtcodequipo.getText();
        nom = txtnombre.getText();
        pais = txtpais.getText();
        idhotel = txtcodigohotel.getText();
        idjuga = txtcodigojugador.getText();
        
        sql = "{ call actualizarinfo_equipos(?,?,?,?,?) }";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro actualizado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para actualizar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO actualizado" + e.getMessage());
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btninformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformeActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,pais,idhotel,idjuga;
        String sql="";
        cod = txtcodequipo.getText();
        nom = txtnombre.getText();
        pais = txtpais.getText();
        idhotel = txtcodigohotel.getText();
        idjuga = txtcodigojugador.getText();
        sql = "SELECT jugadores.nombre_jugador,equipo.idequipo from jugadores "
            + "INNER JOIN equipo ON equipo.idjugadores= jugadores.idjugadores";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tblequipos.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btninformeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmequipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmequipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmequipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmequipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmequipos().setVisible(true);
            }
        });
    }
    
                    public void limpiar()
    {
        txtcodequipo.setText("");
        txtcodigohotel.setText("");
        txtnombre.setText("");
        txtpais.setText("");
        txtcodigojugador.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninforme;
    private javax.swing.JButton btninsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcodequi;
    private javax.swing.JLabel lblcodhotel;
    private javax.swing.JLabel lblcodjugador;
    private javax.swing.JLabel lblequipos;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblpais;
    private javax.swing.JTable tblequipos;
    private javax.swing.JTextField txtcodequipo;
    private javax.swing.JTextField txtcodigohotel;
    private javax.swing.JTextField txtcodigojugador;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpais;
    // End of variables declaration//GEN-END:variables
}
