/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mundial_javamysql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author migue
 */
public class Frmjugadores extends javax.swing.JFrame {

    /**
     * Creates new form Frmjugadores
     */
    public Frmjugadores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lbljugadores = new javax.swing.JLabel();
        lblcodjug = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblcodantidoping = new javax.swing.JLabel();
        txtcodigojug = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtfecha = new javax.swing.JTextField();
        txtcodigotest = new javax.swing.JTextField();
        btnconsultar = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbljugadores = new javax.swing.JTable();
        btninforme = new javax.swing.JButton();
        btninformeantidoping = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbljugadores.setText("JUGADORES");

        lblcodjug.setText("Codigo del Jugador:");

        lblnombre.setText("Nombre:");

        lblfecha.setText("Fecha de Nacimiento:");

        lblcodantidoping.setText("Codigo Test Anti Doping:");

        btnconsultar.setText("Consultar");
        btnconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconsultarActionPerformed(evt);
            }
        });

        btninsertar.setText("Insertar");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        tbljugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane3.setViewportView(tbljugadores);

        btninforme.setText("Generar Informe de Jugadores");
        btninforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformeActionPerformed(evt);
            }
        });

        btninformeantidoping.setText("Generar Informe Anti-Doping del Jugador");
        btninformeantidoping.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninformeantidopingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcodjug)
                            .addComponent(lblnombre)
                            .addComponent(lblfecha)
                            .addComponent(lblcodantidoping))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbljugadores)
                            .addComponent(txtcodigojug, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnombre)
                            .addComponent(txtfecha)
                            .addComponent(txtcodigotest, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btninforme, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btninformeantidoping, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnconsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btninsertar)
                                .addGap(18, 18, 18)
                                .addComponent(btneliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnactualizar))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbljugadores)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblcodjug)
                            .addComponent(txtcodigojug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btninforme)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btninformeantidoping)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnombre)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblfecha)
                    .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcodantidoping)
                    .addComponent(txtcodigotest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconsultar)
                    .addComponent(btninsertar)
                    .addComponent(btneliminar)
                    .addComponent(btnactualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconsultarActionPerformed
        // TODO add your handling code here:
                        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,fecha,idtest;
        String sql="";
        cod = txtcodigojug.getText();
        nom = txtnombre.getText();
        fecha = txtfecha.getText();
        idtest = txtcodigotest.getText();
        sql = "{ call consultarinfo_jugadores(?,?,?,?) }";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tbljugadores.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btnconsultarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        // TODO add your handling code here:
                        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,fecha,idtest;
        String sql= "";
        cod = txtcodigojug.getText();
        nom = txtnombre.getText();
        fecha = txtfecha.getText();
        idtest = txtcodigotest.getText();
        sql = "{ call insertarinfo_jugadores(?,?,?,?) }";
         try {
             PreparedStatement pst = cn.prepareStatement(sql);
             pst.setString(1,cod);
             pst.setString(2,nom);
             pst.setString(3,fecha);
             pst.setString(4,idtest);
             
             int registro=pst.executeUpdate();
             if (registro>0)
             {
                 JOptionPane.showMessageDialog(null, "Registro almacenado correctamente");
                 limpiar();
             }
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Registro NO almacenado " + e.getMessage());

    } 
    }//GEN-LAST:event_btninsertarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,fecha,idtest;
        String sql ="";
        cod = txtcodigojug.getText();
        nom = txtnombre.getText();
        fecha = txtfecha.getText();
        idtest = txtcodigotest.getText();
        sql = "{ call eliminarinfo_jugadores(?,?,?,?) }";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro eliminado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para eliminar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO eliminado" + e.getMessage());
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,fecha,idtest;
        String sql ="";
        cod = txtcodigojug.getText();
        nom = txtnombre.getText();
        fecha = txtfecha.getText();
        idtest = txtcodigotest.getText();
        
        sql = "{ call actualizarinfo_jugadores(?,?,?,?) }";
        System.out.println(sql);
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            
            int registro=pst.executeUpdate();
            if (registro>0)
            {
                JOptionPane.showMessageDialog(null,"Registro actualizado correctamente");
                limpiar();
            }
            else {
                JOptionPane.showMessageDialog(null, "Registro no encontrado para actualizar");
                limpiar();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO actualizado" + e.getMessage());
        }
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btninformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformeActionPerformed
        // TODO add your handling code here:
                conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,fecha,idtest;
        String sql="";
        cod = txtcodigojug.getText();
        nom = txtnombre.getText();
        fecha = txtfecha.getText();
        sql = "SELECT equipo.nombre_equipo,jugadores.nombrejugador from equipo "
            + "INNER JOIN jugadores ON equipo.idjugadores= jugadores.idjugadores";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tbljugadores.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btninformeActionPerformed

    private void btninformeantidopingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninformeantidopingActionPerformed
        // TODO add your handling code here:
        conectar cc = new conectar();
        Connection cn = cc.conexion();
        String cod,nom,fecha,idtest;
        String sql="";
        cod = txtcodigojug.getText();
        nom = txtnombre.getText();
        fecha = txtfecha.getText();
        sql = "SELECT jugadores.nombre_jugador,antidopaje.paso_test from jugadores "
            + "INNER JOIN antidopaje ON jugadores.idjugadores= antidopaje.idjugadores";
        System.out.println(sql);
        
        
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            tbljugadores.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro NO mostrado" + e.getMessage());
        }
    }//GEN-LAST:event_btninformeantidopingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frmjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frmjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frmjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frmjugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frmjugadores().setVisible(true);
            }
        });
    }
    
                public void limpiar()
    {
        txtcodigojug.setText("");
        txtnombre.setText("");
        txtfecha.setText("");
        txtcodigotest.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btninforme;
    private javax.swing.JButton btninformeantidoping;
    private javax.swing.JButton btninsertar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblcodantidoping;
    private javax.swing.JLabel lblcodjug;
    private javax.swing.JLabel lblfecha;
    private javax.swing.JLabel lbljugadores;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JTable tbljugadores;
    private javax.swing.JTextField txtcodigojug;
    private javax.swing.JTextField txtcodigotest;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
